db = { include required("autolab_db.conf") }
sut = { include required("autolab_sut_base.conf") }
sut = {
    command-line-addition = ["--example", "AssessmentsController#index"],
}
solver = {
    tbl-row-bound = 2,
    query-row-bound = 1
}
scalar-inputs = [
    { name = "now", vk = "timestamp" },
    { name = "user_id", vk = "long" },
    { name = "course_name", vk = "string", constraints = [ { type = "string-not-empty" } ] },
]

