query = {
  type = "codex",
  app-dir = "/home/ubuntu/dse/Autolab",
  include "codex.conf"
}
conditional = {
  type = "codex",
  app-dir = "/home/ubuntu/dse/Autolab",
  include "codex.conf"
}
include "autolab_oracle_norm.conf"
codex-parallelism = 16
