jdbc-url = "jdbc:mysql://localhost:3306/autolab_test?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&character_set_server=utf8mb4&collation_server=utf8mb4_bin,autolab_test",
jdbc-driver-class = "com.mysql.cj.jdbc.Driver",
user-name = "autolab",
password = "12345678",
tbl-name-ignore-regexes = ["ar_internal_metadata", "schema_migrations", "module_.*"],
include required("autolab_db_constraints.conf")
