db = { include required("autolab_db.conf") }
sut = { include required("autolab_sut_base.conf") }
sut = {
    command-line-addition = ["--example", "AssessmentsController#viewGradesheet"],
}
solver = { include required("autolab_solver.conf") }
oracle = { include required("autolab_oracle.conf") }
scalar-inputs = [
    { name = "now", vk = "timestamp" },
    { name = "user_id", vk = "long" },
    { name = "course_name", vk = "string", constraints = [ { type = "string-not-empty" } ] },
    { name = "assessment_name", vk = "string", constraints = [ { type = "string-not-empty" } ] },
]

