db = { include required("diaspora_db.conf") }
sut = { include required("diaspora_sut_base.conf") }
sut = {
    command-line-addition = ["--example", "PeopleController#stream"],
}
sym-db = {
    row-bound = 1,
}
scalar-inputs = [
    { variable = { name = "user_id", kind = "long" } },
    { variable = { name = "person_guid", kind = "string" }, constraints = [ { type = "string-not-empty" } ] },
]

