cwd = "/home/ubuntu/dse/diaspora"

// mode = { type = "concurrent-socket", concurrency: 2 }
// command-line-base = ["/home/ubuntu/dse/examples/run_diaspora_docker.sh", "spec/controllers/invoke_all_controller_spec.rb"]

mode = { type = "socket" }
command-line-base = ["/home/ubuntu/dse/jruby/bin/ruby", "-Xconsistent.hashing=true", "/home/ubuntu/dse/diaspora/bin/rspec_dse", "spec/controllers/invoke_all_controller_spec.rb"]

