db = { include required("diaspora_db.conf") }
sut = { include required("diaspora_sut_base.conf") }
sut = {
    command-line-addition = ["--example", "PostsController#show"],
}
sym-db = {
    row-bound = 1,
}
scalar-inputs = [
    { name = "now", kind = "timestamp" },
    { name = "user_id", kind = "long" },
    { name = "post_id", kind = "long" },
]

