db = { include required("diaspora_db.conf") }
sut = { include required("diaspora_sut_base.conf") }
sut = {
    command-line-addition = ["--example", "PostsController#show"],
}
solver = { include required("diaspora_solver.conf") }
oracle = { include required("diaspora_oracle.conf") }
scalar-inputs = [
    { name = "now", vk = "timestamp" },
    { name = "user_id", vk = "long" },
    { name = "post_id", vk = "long" },
]

