db = { include required("diaspora_db.conf") }
sut = { include required("diaspora_sut_base.conf") }
sut = {
    command-line-addition = ["--example", "PeopleController#show"],
}
solver = {
    tbl-row-bound = 2,
    query-row-bound = 1
}
oracle = { include required("diaspora_oracle.conf") }
scalar-inputs = [
    { name = "now", vk = "timestamp" },
    { name = "user_id", vk = "long" },
    { name = "person_guid", vk = "string", constraints = [ { type = "string-not-empty" } ] },
]

