query = {
  type = "codex",
  app-dir = "/home/ubuntu/dse/diaspora",
  include "codex.conf"
}
conditional = {
  type = "codex",
  app-dir = "/home/ubuntu/dse/diaspora",
  include "codex.conf"
}
include "oracle_normalization.conf"
codex-parallelism = 1
