jdbc-url = "jdbc:mysql://localhost:3306/diaspora_test?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&character_set_server=utf8mb4&collation_server=utf8mb4_bin,diaspora_test",
jdbc-driver-class = "com.mysql.cj.jdbc.Driver",
user-name = "diaspora",
password = "12345678",
tbl-name-ignore-regexes = ["ar_internal_metadata", "schema_migrations"],
include required("diaspora_db_constraints.conf")
