db = { include required("diaspora_db.conf") }
// sut = { include required("diaspora_sut_base.conf") }
// sut = {
//     command-line-addition = ["--example", "PostsController#show"],
// }
sut = {
    cwd = "/home/ubuntu/dse/diaspora",
    mode = { type = "concurrent-socket", concurrency: 2 },
    command-line-base = ["/home/ubuntu/dse/examples/unixsock2http.py", "http://34.173.58.194"],
    command-line-addition = []
}
solver = {
    tbl-row-bound = 2,
    query-row-bound = 1
}
scalar-inputs = [
    { name = "now", vk = "timestamp" },
    { name = "user_id", vk = "long" },
    { name = "post_id", vk = "long" },
]

