query = {
  type = "codex",
  app-dir = "/home/ubuntu/dse/diaspora",
  include "codex_options.conf"
}
conditional = {
  type = "codex",
  app-dir = "/home/ubuntu/dse/diaspora",
  include "codex_options.conf"
}
truncate-stacktrace-after = "/diaspora/app/"
