db = { include required("diaspora_db.conf") }
sut = { include required("diaspora_sut_base.conf") }
sut = {
    command-line-addition = ["--example", "CommentsController#index"],
}
solver = {
    tbl-row-bound = 2,
    query-row-bound = 1
}
scalar-inputs = [
    { variable = { name = "user_id", kind = "long" } },
    { variable = { name = "post_id", kind = "long" } },
]

