query = { type = "codex", app-dir = "/home/ubuntu/dse/diaspora", extra-args = ["--model", "gpt-5"] }
conditional = { type = "codex", app-dir = "/home/ubuntu/dse/diaspora", extra-args = ["--model", "gpt-5"] }
truncate-stacktrace-after = "/diaspora/app/"
