db = { include required("theodinproject_db.conf") }
sut = { include required("theodinproject_sut_base.conf") }
sut = {
    command-line-addition = ["--example", "StaticPagesController#success_stories"],
}
solver = { include required("theodinproject_solver.conf") }
scalar-inputs = [
    { name = "now", vk = "timestamp" },
    { name = "user_id", vk = "long" },
]

