db = { include required("theodinproject_db.conf") }
sut = { include required("theodinproject_sut_base.conf") }
sut = {
    command-line-addition = ["--example", "CoursesController#show"],
}
solver = { include required("theodinproject_solver.conf") }
scalar-inputs = [
    { name = "now", vk = "timestamp" },
    { name = "user_id", vk = "long" },
    { name = "path_id", vk = "string",
      // The `friendly_id` gem performs unsupported type conversions when `path_id` encodes an integer.
      // So we want to constrain `path_id` to be non-integer strings.  But our SMT string encoding
      // doesn't support that.  So we constrain it to one of several good values...
      constraints = [ { type = "string-one-of", values = ["path-1", "path-2", "path-3"] } ]
    },
    { name = "course_id", vk = "string",
      // Same as above.
      constraints = [ { type = "string-one-of", values = ["course-1", "course-2", "course-3"] } ]
    },
]

