db = { include required("theodinproject_db.conf") }
sut = { include required("theodinproject_sut_base.conf") }
sut = {
    command-line-addition = ["--example", "Lessons::ProjectSubmissionsController#index"],
}
solver = { include required("theodinproject_solver.conf") }
scalar-inputs = [
    { name = "now", vk = "timestamp" },
    { name = "user_id", vk = "long" },
    { name = "lesson_id", vk = "string",
      constraints = [ { type = "string-one-of", values = ["lesson-1", "lesson-2", "lesson-3"] } ]
    },
]

